// Build the C# sensor sidecar and embed it (plus the vendored LibreHardwareMonitor
// DLLs) into the binary as a generated manifest.
//
// The sidecar is compiled with the in-box .NET Framework C# compiler (csc.exe) —
// no .NET SDK is required, since LibreHardwareMonitor targets .NET Framework 4.7.2
// which ships with every supported version of Windows.
//
// `install` later extracts SENSOR_ASSETS (sidecar exe + DLLs) side by side into
// C:\ProgramData\WatchDesk\sensors\, where the service spawns the sidecar.
use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let sidecar_src = manifest_dir.join("sidecar").join("WatchdeskSensors.cs");
    let vendor_dir = manifest_dir.join("vendor").join("lhm");
    let lhm_lib = vendor_dir.join("LibreHardwareMonitorLib.dll");
    let sidecar_exe = out_dir.join("watchdesk-sensors.exe");

    println!("cargo:rerun-if-changed={}", sidecar_src.display());

    // Compile the sidecar against the vendored LibreHardwareMonitor library.
    let csc = find_csc().expect(
        "csc.exe (.NET Framework 4.x) not found under C:\\Windows\\Microsoft.NET — \
         it is required to build the WatchDesk sensor sidecar",
    );
    let status = Command::new(&csc)
        .args(["/nologo", "/target:exe", "/platform:x64", "/optimize+"])
        .arg(format!("/out:{}", sidecar_exe.display()))
        .arg(format!("/reference:{}", lhm_lib.display()))
        .arg(&sidecar_src)
        .status()
        .expect("failed to launch csc.exe");
    assert!(
        status.success(),
        "sidecar compilation failed (csc exit {:?})",
        status.code()
    );

    // Collect assets to embed: the sidecar exe + every vendored DLL.
    let mut assets: Vec<(String, PathBuf)> = vec![("watchdesk-sensors.exe".into(), sidecar_exe)];
    let mut dlls: Vec<PathBuf> = fs::read_dir(&vendor_dir)
        .expect("vendor/lhm directory not found")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("dll"))
        .collect();
    dlls.sort();
    for dll in dlls {
        println!("cargo:rerun-if-changed={}", dll.display());
        let name = dll.file_name().unwrap().to_string_lossy().into_owned();
        assets.push((name, dll));
    }

    // Emit the manifest consumed via include! in main.rs.
    let mut code = String::from(
        "// @generated by build.rs — sidecar exe + vendored LibreHardwareMonitor DLLs.\n\
         pub static SENSOR_ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for (name, path) in &assets {
        code.push_str(&format!(
            "    (\"{}\", include_bytes!(r\"{}\")),\n",
            name,
            path.display()
        ));
    }
    code.push_str("];\n");
    fs::write(out_dir.join("sensor_assets.rs"), code).unwrap();
}

fn find_csc() -> Option<PathBuf> {
    for candidate in [
        r"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe",
        r"C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe",
    ] {
        let path = PathBuf::from(candidate);
        if path.exists() {
            return Some(path);
        }
    }
    None
}
