[package]
description = "A service that publishes PC status (monitor state, CPU usage & temperature) to Home Assistant over MQTT"
license = "MIT"
repository = "https://github.com/meltingice1337/watchdesk"
categories = ["monitoring", "mqtt", "homeassistant"]
keywords = ["mqtt", "homeassistant", "monitoring", "pc status"]
readme = "README.md"
name = "watchdesk"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-service = "0.8"
windows = { version = "0.62.2", features = [
  "Win32_System_Power",
  "Win32_System_SystemServices",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Shell",
  "Win32_Foundation",
  "Win32_System_LibraryLoader",
  "Win32_System_Threading",
  "Win32_Security",
  "Win32_Graphics_Gdi",
  "Win32_System_Registry",
] }
rumqttc = "0.25.1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
toml = "0.9.8"
log = "0.4"
env_logger = "0.11"
clap = { version = "4", features = ["derive"] }
serde_json = "1"
anyhow = "1"
sysinfo = "0.33"
